version: "3.8"

services:
  app:
    build: .
    container_name: encomendas-app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: encomendas-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=encomendas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
